### ISSUE TITLE
Compiled mex-file uses matlab's QT library instead of the user installed ones

### ISSUE THREAD

**Issue by piermorel** [dashesy/CereLink#10]
Hello,

For a long time I couldn't get cbmex to work in matlab on the mac (I was getting a QT version error, even though I installed and compiled with the correct version). I realized that the mex file was by default using matlab's own QT libraries (contained in MATLAB_R2011b/bin/maci64)… and the only solution I found was to actually replace the libraries inside matlab's bundle by more recent ones. But I'm afraid it's not a very good solution and might affect matlab's (relative) stability. Is there a way (either in matlab, or with cmake) to have the mex file load the "normal" libraries (/usr/local/lib) ?

**Comment by dashesy** [comment]
LD_PRELOAD_LIBRARY can be used, otherwise now we can run in Octave that will be a much smoother experience.
