### ISSUE TITLE
How to get events (digital_events) from NSP by using cbpy?

### ISSUE THREAD

**Issue by Qifan94** [dashesy/CereLink#108]
Hi, I am using NSP connected to a Windows computer and another Ubuntu computer to use cbpy to get neural data in real-time. By using the python wrapper, I can connect to NSP and get the spike event time successfully. But the variable `events` is always empty. 

```
def trial_event(int instance=0, bool reset=False, bool reset_clock=False):
    ''' Trial spike and event data.
    Inputs:
       instance 
       reset
       reset_clock 
    Outputs:
       list of arrays [channel, {'timestamps':[unit0_ts, ..., unitN_ts], 'events':digital_events}]
           channel: integer, channel number (1-based)
           digital_events: array, digital event values for channel (if a digital or serial channel)
           unitN_ts: array, spike timestamps of unit N for channel (if an electrode channel));

```
I believed that `digital_events` here is the variable which is event markers given by digital inputs of the task events (such as trail start, movement onset et al.). please correct me if this is not true.

Below is the script that I am using to try :

```
import time
from cerebus import cbpy
import numpy as np

buffer_par = {'double':True,'continuous_length':15000,'event_length':100} #set buffer
        cbpy.open()
        cbpy.trial_config(instance=0,reset=True,buffer_parameter=self.buffer_par,range_parameter={},noevent=0,nocontinuous=0,nocomment=0)
dig,event= cbpy.trial_event(instance=0,reset=True, reset_clock=True) #flush buffer
time.sleep(0.5)
dig,event= cbpy.trial_event(instance=0,reset=True, reset_clock=True) #read buffer

```
Thanks!

**Comment by Qifan94** [comment]
BTW, I checked the NSP system can record the digital events sent by a NI card well.

**Comment by cboulay** [comment]
Hi, sorry for the delay in replying.

Are you using the latest wheel from the release page: https://github.com/dashesy/CereLink/releases/tag/v7.0.4 ? There were some bugs in how digital events were read in but they were fixed.

If you are using the latest wheel and the problem persists, then please upload a small test file that has some of your digital events then I will try to reproduce the error locally using file playback.

**Comment by Qifan94** [comment]
[small test data.zip](https://github.com/dashesy/CereLink/files/3504095/small.test.data.zip)

Thanks for your reply. The 10-trial small test data with the digital event is attached. 
Each trial should start with event '9' and stop with the event '18'.
I am looking forward to receiving your reply soon.

**Comment by cboulay** [comment]
I finally got around to testing and everything seems OK on my end. I played your file back through NPlayServer, and I used the same script as in [this comment](https://github.com/dashesy/CereLink/issues/103#issuecomment-486534360), and here's the output I got (you can probably ignore the timestamp list in the 3rd column of each row: 

```
1 1 [0] [0]
2 1 [106792] [9]
3 1 [107805] [24]
4 1 [110023] [1]
5 1 [150505] [2]
6 1 [166524] [3]
7 1 [179523] [4]
8 1 [192550] [5]
9 1 [197203] [6]
10 1 [203523] [8]
11 1 [214711] [10]
12 1 [242015] [18]
13 1 [305805] [9]
14 1 [306024] [1]
15 1 [317928] [2]
16 1 [333524] [3]
17 1 [349523] [4]
18 1 [359899] [5]
19 1 [363536] [6]
20 1 [370023] [8]
21 1 [378617] [10]
22 1 [405686] [18]
23 1 [466549] [9]
24 1 [467025] [1]
25 1 [477407] [2]
26 1 [492523] [3]
27 1 [509024] [4]
28 1 [520547] [5]
29 1 [524625] [6]
30 1 [531024] [7]
32 2 [539421 539431] [10 18]
34 2 [599908 600024] [9 1]
35 1 [617452] [2]
36 1 [633024] [3]
37 1 [651024] [4]
38 1 [664353] [5]
39 1 [668692] [6]
40 1 [675024] [8]
41 1 [682947] [10]
42 1 [709995] [18]
43 1 [770423] [9]
44 1 [770523] [1]
45 1 [770880] [2]
46 1 [786524] [3]
47 1 [802024] [4]
48 1 [813270] [5]
49 1 [818570] [6]
50 1 [825024] [8]
51 1 [834626] [10]
52 1 [861668] [18]
53 1 [922183] [9]
54 1 [922524] [1]
55 1 [922991] [2]
56 1 [926151] [18]
58 2 [986465 986524] [9 1]
59 1 [991147] [2]
60 1 [1006524] [3]
61 1 [1021524] [4]
62 1 [1033220] [5]
63 1 [1035998] [6]
64 1 [1042524] [8]
65 1 [1083997] [10]
66 1 [1111034] [18]
68 2 [1171495 1171524] [9 1]
69 1 [1183502] [2]
70 1 [1199024] [3]
71 1 [1215024] [4]
72 1 [1227090] [5]
73 1 [1230406] [6]
74 1 [1236524] [8]
75 1 [1249228] [10]
76 1 [1276256] [18]
77 1 [1336712] [9]
78 1 [1337024] [1]
79 1 [1351955] [2]
80 1 [1367524] [3]
81 1 [1381524] [4]
82 1 [1392252] [5]
83 1 [1394935] [6]
84 1 [1401524] [7]
86 2 [1408833 1408843] [10 18]
87 1 [1469282] [9]
88 1 [1469524] [1]
89 1 [1483473] [2]
90 1 [1499024] [3]
91 1 [1512024] [4]
92 1 [1524793] [5]
93 1 [1529463] [6]
94 1 [1536024] [7]
96 2 [1548846 1548856] [10 18]
97 1 [1609314] [9]
98 1 [1609524] [1]
99 1 [1670031] [18]
```

Make sure you're using the latest wheel from the release page or that you've built from the latest source code.

**Comment by cboulay** [comment]
Please reopen this if you're still having trouble after installing the latest version of cbpy.

**Comment by Qifan94** [comment]
Hi, thanks a lot for your patient. 

I use the latest version and try to get event again. And I can get the event sometimes, like 30% chance. 

I used `cbpy.open()` then tried to get trial event. But it was not that stable, if the 'event' was empty, I tried to close and reopen it serval times, and then it worked. When it works, you can get the event continuously with. However, if you closed and reopened it, it did not work again. So I am quite confused.

 Do you have any idea about this situation?
