### ISSUE TITLE
Help building on Windows 10: VCInstallDir

### ISSUE THREAD

**Issue by charlesincharge** [dashesy/CereLink#113]
I'd like to use cbpy, but I'm having trouble building the CereLink libraries. I ran `cmake .. -G "Visual Studio 15 2017 Win64" -DQt5_DIR=C:\Qt\5.14.1\msvc2017_64\lib\cmake\Qt5 -DCMAKE_INSTALL_PREFIX=..\dist -DBUILD_CLI=ON` successfully.

However, when trying to build, I get warnings about `Cannot find Visual Studio installation directory, VCINSTALLDIR is not set` and `The type or namespace name 'CereLink' could not be found (are you missing a using directive or an assembly reference?`. Tried a few values for VCINSTALLDIR env variable but it doesn't seem to work.  Would you be able to help me understand how to fix this?

I am running:
* Windows 10
* Anaconda Powershell - Python 3.6 (also tried cmd but received the same error)
* Visual Studio 2017 Community

Best,
Charles
Grad student

Below is the full log.
`(cbpy) PS C:\Users\charles\Development\CereLink\build> cmake --build . --config Release
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  cbsdk.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\cbsdk.dll
  cbsdk_cli.vcxproj -> C:\Users\charles\Development\CereLink\dist\lib64\cbsdk_cli.dll
  cbsdk_static.vcxproj -> C:\Users\charles\Development\CereLink\dist\lib64\cbsdk_static.lib
  cbmex.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\cbmex.mexw64
  cbsdk_ext.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\cbsdk_ext.dll
  test_analog_out.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\test_analog_out.exe
  C:\Users\charles\Development\CereLink\dist\bin\cbsdk.dll 64 bit, release executable
  Direct dependencies: Qt5Core Qt5Xml
  All dependencies   : Qt5Core Qt5Xml
  To be deployed     : Qt5Core Qt5Xml
EXEC : warning : Cannot find Visual Studio installation directory, VCINSTALLDIR is not set. [C:\Users\charles\Developme
nt\CereLink\build\test_analog_out.vcxproj]
  Qt5Core.dll is up to date.
  Qt5Xml.dll is up to date.
  Creating qt_ar.qm...
  Creating qt_bg.qm...
  Creating qt_ca.qm...
  Creating qt_cs.qm...
  Creating qt_da.qm...
  Creating qt_de.qm...
  Creating qt_en.qm...
  Creating qt_es.qm...
  Creating qt_fi.qm...
  Creating qt_fr.qm...
  Creating qt_gd.qm...
  Creating qt_he.qm...
  Creating qt_hu.qm...
  Creating qt_it.qm...
  Creating qt_ja.qm...
  Creating qt_ko.qm...
  Creating qt_lv.qm...
  Creating qt_pl.qm...
  Creating qt_ru.qm...
  Creating qt_sk.qm...
  Creating qt_uk.qm...
  Creating qt_zh_TW.qm...
  test_comments.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\test_comments.exe
  C:\Users\charles\Development\CereLink\dist\bin\cbsdk.dll 64 bit, release executable
  Direct dependencies: Qt5Core Qt5Xml
  All dependencies   : Qt5Core Qt5Xml
  To be deployed     : Qt5Core Qt5Xml
EXEC : warning : Cannot find Visual Studio installation directory, VCINSTALLDIR is not set. [C:\Users\charles\Developme
nt\CereLink\build\test_comments.vcxproj]
  Qt5Core.dll is up to date.
  Qt5Xml.dll is up to date.
  Creating qt_ar.qm...
  Creating qt_bg.qm...
  Creating qt_ca.qm...
  Creating qt_cs.qm...
  Creating qt_da.qm...
  Creating qt_de.qm...
  Creating qt_en.qm...
  Creating qt_es.qm...
  Creating qt_fi.qm...
  Creating qt_fr.qm...
  Creating qt_gd.qm...
  Creating qt_he.qm...
  Creating qt_hu.qm...
  Creating qt_it.qm...
  Creating qt_ja.qm...
  Creating qt_ko.qm...
  Creating qt_lv.qm...
  Creating qt_pl.qm...
  Creating qt_ru.qm...
  Creating qt_sk.qm...
  Creating qt_uk.qm...
  Creating qt_zh_TW.qm...
  test_io.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\test_io.exe
  C:\Users\charles\Development\CereLink\dist\bin\cbsdk.dll 64 bit, release executable
  Direct dependencies: Qt5Core Qt5Xml
  All dependencies   : Qt5Core Qt5Xml
  To be deployed     : Qt5Core Qt5Xml
EXEC : warning : Cannot find Visual Studio installation directory, VCINSTALLDIR is not set. [C:\Users\charles\Developme
nt\CereLink\build\test_io.vcxproj]
  Qt5Core.dll is up to date.
  Qt5Xml.dll is up to date.
  Creating qt_ar.qm...
  Creating qt_bg.qm...
  Creating qt_ca.qm...
  Creating qt_cs.qm...
  Creating qt_da.qm...
  Creating qt_de.qm...
  Creating qt_en.qm...
  Creating qt_es.qm...
  Creating qt_fi.qm...
  Creating qt_fr.qm...
  Creating qt_gd.qm...
  Creating qt_he.qm...
  Creating qt_hu.qm...
  Creating qt_it.qm...
  Creating qt_ja.qm...
  Creating qt_ko.qm...
  Creating qt_lv.qm...
  Creating qt_pl.qm...
  Creating qt_ru.qm...
  Creating qt_sk.qm...
  Creating qt_uk.qm...
  Creating qt_zh_TW.qm...
  testcbsdk.vcxproj -> C:\Users\charles\Development\CereLink\dist\bin\testcbsdk.exe
  C:\Users\charles\Development\CereLink\dist\bin\cbsdk.dll 64 bit, release executable
  Direct dependencies: Qt5Core Qt5Xml
  All dependencies   : Qt5Core Qt5Xml
  To be deployed     : Qt5Core Qt5Xml
EXEC : warning : Cannot find Visual Studio installation directory, VCINSTALLDIR is not set. [C:\Users\charles\Developme
nt\CereLink\build\testcbsdk.vcxproj]
  Qt5Core.dll is up to date.
  Qt5Xml.dll is up to date.
  Creating qt_ar.qm...
  Creating qt_bg.qm...
  Creating qt_ca.qm...
  Creating qt_cs.qm...
  Creating qt_da.qm...
  Creating qt_de.qm...
  Creating qt_en.qm...
  Creating qt_es.qm...
  Creating qt_fi.qm...
  Creating qt_fr.qm...
  Creating qt_gd.qm...
  Creating qt_he.qm...
  Creating qt_hu.qm...
  Creating qt_it.qm...
  Creating qt_ja.qm...
  Creating qt_ko.qm...
  Creating qt_lv.qm...
  Creating qt_pl.qm...
  Creating qt_ru.qm...
  Creating qt_sk.qm...
  Creating qt_uk.qm...
  Creating qt_zh_TW.qm...
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(
2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "cbsdk_cli". Check to make su
re the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\c
harles\Development\CereLink\build\cli\TestCLI\TestCLI.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,
5): warning MSB3052: The parameter to the compiler is invalid, '/define:WINVER=0x0501' will be ignored. [C:\Users\charl
es\Development\CereLink\build\cli\TestCLI\TestCLI.csproj]
C:\Users\charles\Development\CereLink\cli\TestCLI\Program.cs(6,7): error CS0246: The type or namespace name 'CereLink'
could not be found (are you missing a using directive or an assembly reference?) [C:\Users\charles\Development\CereLink
\build\cli\TestCLI\TestCLI.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,
5): warning MSB3052: The parameter to the compiler is invalid, '/define:WINVER=0x0501' will be ignored. [C:\Users\charl
es\Development\CereLink\build\cli\TestCSharp\TestCSharp.csproj]
C:\Users\charles\Development\CereLink\cli\TestCSharp\Program.cs(30,50): error CS8024: Feature 'out variable declaration
' is not available in C# 3. Please use language version 7.0 or greater. [C:\Users\charles\Development\CereLink\build\cl
i\TestCSharp\TestCSharp.csproj]`

**Comment by cboulay** [comment]
I’m on mobil, sorry for short replies. Please make sure you use visual studio command prompt (x64 native or something like that), and not powershell or vanilla cmd . And if you don’t need the c# stuff then disable that via cmake (sorry not sure right now how to do that)

**Comment by charlesincharge** [comment]
Okay, I'll give that a try. Thanks!

**Comment by charlesincharge** [comment]
Using the Developer command prompt helped, although I ran into a different issue now:

```
(cbpy) PS C:\Users\charles\Development\CereLink\samples\Python> python .\fetch_data_continuous.py
Traceback (most recent call last):
  File ".\fetch_data_continuous.py", line 3, in <module>
    from cerebus import cbpy
ImportError: DLL load failed: The specified procedure could not be found.
```
How can I tell which DLLs this refers to? Searched on StackOverflow to no avail, and I tried moving around the Qt DLLs into different Anaconda environments, etc, but I still get the same error

Fyi, I'm starting from a relatively clean Anaconda (Python 3.6) environment:
```
(cbpy) PS C:\Users\charles\Development\CereLink\samples\Python> conda list
# packages in environment at C:\Users\charles\Anaconda3\envs\cbpy:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
cerebus                   0.0.4                    pypi_0    pypi
certifi                   2019.11.28               py36_0
cython                    0.29.14          py36ha925a31_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.4                      245
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.15           py36h14836fe_0
mkl_random                1.1.0            py36h675688f_0
numpy                     1.18.1           py36h93ca92e_0
numpy-base                1.18.1           py36hc3f5095_1
pip                       20.0.2                   py36_1
python                    3.6.10               h9f7ef89_0
setuptools                45.1.0                   py36_0
six                       1.14.0                   py36_0
sqlite                    3.30.1               he774522_0
vc                        14.1                 h0510ff6_4    anaconda
vs2015_runtime            14.16.27012          hf0eaf9b_1    anaconda
wheel                     0.34.1                   py36_0
wincertstore              0.2              py36h7fe50ca_0
```

**Comment by cboulay** [comment]
‘pip install pylsl’
If you are only using python then you never needed to build the library.

**Comment by cboulay** [comment]
Try these instructions. 
https://github.com/dashesy/CereLink/blob/master/BUILD.md#cerebus-python-lib-build-instructions

**Comment by charlesincharge** [comment]
I had followed those instructions, but unfortunately I'm still getting this error:
```
(cbpy) PS C:\Users\charles\Development\CereLink\samples\Python> python .\fetch_data_continuous.py
Traceback (most recent call last):
  File ".\fetch_data_continuous.py", line 3, in <module>
    from cerebus import cbpy
ImportError: DLL load failed: The specified procedure could not be found.
```
I'm using Qt 5.14.1 - I can try dropping down to Qt 5.13.1

**Comment by cboulay** [comment]
If the `pip install .` worked then I don't see what the problem could be. It's not the Qt version. I was just giving an example command in that BUILD.md doc, I didn't mean to imply a specific version was required. Any recent Qt should work, and I'm pretty sure it's only needed during build so lack of Qt DLL at runtime isn't the problem.

Maybe you're missing a msvc runtime? From within your conda environment, run [Dependencies.exe](https://github.com/lucasg/Dependencies/releases) and analyze the cbpy.pyd file somewhere in your {/path/to/anaconda/env}/lib/site-packages/cerebus/ folder. That will tell you what dlls it can't find.

**Comment by cboulay** [comment]
Here are the contents of my `C:\Users\Chad\.conda\envs\cerebus_test\Lib\site-packages\cerebus` folder.

> 2019-08-19  09:22 PM           361,472 cbpy.cp36-win_amd64.pyd
> 2019-08-19  09:20 PM           301,568 cbsdk.dll
> 2019-08-19  09:20 PM         5,892,608 Qt5Core.dll
> 2018-06-15  12:11 AM           195,072 Qt5Xml.dll

**Comment by charlesincharge** [comment]
I did a clean install of Qt and a clean build, and it's working now. Not 100% what went wrong, but it's possible that I had the wrong Qt5Core.dll / Qt5Xml.dll copied to my conda site-packages at first. Thanks for your help!

**Comment by charlesincharge** [comment]
making a note that `cmake .. -G "Visual Studio 15 2017 Win64" -DQt5_DIR=C:\Qt\5.14.2\msvc2017_64\lib\cmake\Qt5 -DCMAKE_INSTALL_PREFIX=..\dist -DBUILD_CLI=OFF` <- C# off seems to  help
