### ISSUE TITLE
n2h5 seg fault

### ISSUE THREAD

**Issue by sdangi** [dashesy/CereLink#39]
On linux (Ubuntu 12.04 LTS), n2h5 seems to work (it creates a non-empty, seemingly-correct hdf file), but it terminates with a seg fault:

```sh
$ n2h5 test.nev test.nev.hdf
Segmentation fault (core dumped)
```

However, there is no seg fault on OS X.  Since it seems to work, this is not strictly a problem, but still it's strange that it seg faults.  Note that in order to be able to build n2h5 at all, I had to install hdf5 from source (in case this helps diagnose the problem):

```sh
wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.13.tar.gz
tar zxvf hdf5-1.8.13.tar.gz
cd hdf5-1.8.13
./configure --prefix=/usr
sudo make
sudo make install
```

**Comment by dashesy** [comment]
sorry this is taking too much time, if I get a small nev file that shows this problem, will fix this.

**Comment by dashesy** [comment]
It should be fixed now with a workaround, it was actually a bug in HDF5. Had to manually go through PT and close them, even though process was going to exit anyways, otherwise H5PTclose was resulting in SIGSEV. The right thing to do is file a bug with HDF5 project.
