### ISSUE TITLE
cbSdkGetChannelConfig returns error when querying valid channels.

### ISSUE THREAD

**Issue by griffinmilsap** [dashesy/CereLink#40]
**Problem:**
Querying some channels results in `CBSDKRESULT_INVALIDCHANNEL` even if they are valid channels.

**System Configuration:** 
- NSP version 6.03 firmware
- Latest CBSDK, compiled as DLL in Visual Studio 2008 on Windows 8.1
- Dynamically linked cbsdk.dll in a BCI2000 Source module compiled with Visual Studio 2008 on Windows 8.1
- [This representative development configuration.](https://db.tt/NmrUlYDT)

**Detailed Description:**
The following code segment illustrates the problem concisely.  Given a sample group (in this case 4), the code queries for the number of channels currently belonging to that sample group using cbSdkGetSampleGroupList.  If there is a non-zero amount of channels, it uses cbSdkGetChannelConfig to retrieve a structure containing information about the channel.  The code is supposed to pull the channel name from that channel and write it to the debug log.

In the following code segment, CereLinkError is a function that accepts a cbSdkResult as an input. It returns true and prints an error message to the debug log if and only if the result is an error.  CereLinkError otherwise returns false if the API call is successful or results in a warning.  `bcidbg` and `bcierr` are debug and error logs, respectively.

```
#define INST 0


// Get the length of the channel list for this sample group
unsigned int nLength = 0;
CereLinkError( cbSdkGetSampleGroupList( INST, 1, group, &nLength, NULL ) );

// If this sample group has channels, let's query them!
if( nLength != 0 )
{
  // Get the list of channels in this sample group
  unsigned int *pGroupList = new unsigned int[ nLength ];
  CereLinkError( cbSdkGetSampleGroupList( INST, 1, group, &nLength, pGroupList ) );

  // For each channel in the list
  for( unsigned int ch_idx = 0; ch_idx < nLength; ch_idx++ )
  {
    cbPKT_CHANINFO* pChanInfo = new cbPKT_CHANINFO();
    if( !CereLinkError( cbSdkGetChannelConfig( INST, pGroupList[ ch_idx ], pChanInfo ) ) ) 
    {
      string strLabel = string( pChanInfo->label );
      bcidbg( 0 ) << strLabel;
    } else bcidbg( 0 ) << "Bad Channel Index: " << pGroupList[ ch_idx ] << endl;
    delete pChanInfo;
  }
  delete [] pGroupList;

  // Set the source parameters accordingly

} else
  bcierr << "There are no channels sampled at the desired SamplingRate." << endl;
```

**Expected result:**
In the requested sample group, all channel labels are printed to the debug log.
**Actual result:**
[Given a test config](https://db.tt/NmrUlYDT), a list of 124 channel indices is returned by cbSdkGetSampleGroupList, with group 4 requested.  Channel indices 1-59 print their names to the debug log, channel indices 60-71 result in the error `CBSDKRESULT_INVALIDCHANNEL` being thrown, then channels 72-88 print their names to the debug log, then channels 89+ all throw `CBSDKRESULT_INVALIDCHANNEL`.

**Insights:** Looking through the CBSDK code, the only way these errors could be being thrown is if `cb_cfg_buffer_ptr[nIdx]->chaninfo[chan - 1].chid == 0` on [line 1591 of cbhwlib.cpp](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.cpp#L1591).  Apparently, the `cb_cfg_buffer_ptr` structure is populated on [line 359 of cbhwlib.cpp](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.cpp#L359) in cbOpen using some shared memory mapping function, found on [line 259 of cbhwlib.cpp](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.cpp#L259).  This leads me to one of two conclusions:
- The memory map isn't being interpreted correctly due to some architectural differences?
- The shared memory block isn't being populated properly (possibly an issue in the NSP firmware)?

**Further Testing:**  I've confirmed that the problem also exists in the [MFC sample program](https://github.com/dashesy/CereLink/blob/master/samples/SDKSample/SDKSampleDlg.cpp).  I have not yet tested other Windows platforms, compilers, or NSP firmware versions.  I am unable to test the 6.04 firmware due to it not being FDA approved yet, so we cannot update our clinical system.

**Comment by FloFra** [comment]
You will have the same problem when using cbsdk with hwlib 3.9 (the current version right now) and an instrument that runs hwlib 3.10 (the latest versions shipped with Central).

**Comment by dashesy** [comment]
Yes, it will not work. Only matching versions will work, mainly because the packet sizes do change from version to version.
