### ISSUE TITLE
SDKSample does not compile when build against MFC Unicode version

### ISSUE THREAD

**Issue by FlorianFranzen** [dashesy/CereLink#46]
The Multi-Byte Character Set (MBCS) version of MFC is marked as deprecated starting with VS 2013 and therefore no longer included. When trying to build the SDKSample against the now default Unicode version, there are a bunch of `LPCTSTR` related casting errors.

Installing the [MFC MBCS DLL Add-on](https://www.microsoft.com/en-us/download/details.aspx?id=40770) and building against the MBSC version works fine, so this is probably a good workaround for now.

**Comment by dashesy** [comment]
There *was* no real MB support in `cbhwlib`, and I do not think there is now, so we should be safe to just rename all to `char *`. This whole all-caps Microsoft types are ugly and confusing.

**Comment by dashesy** [comment]
Added this to wiki
