### ISSUE TITLE
Do not use windows.h min and max

### ISSUE THREAD

**Issue by FlorianFranzen** [dashesy/CereLink#51]
Currently CereLink uses the min and max defined in `windows.h`. For any other platform than windows, [compat.h](https://github.com/dashesy/CereLink/blob/master/cbhwlib/compat.h) defines min and max macros.

I think CereLink should instead be compiles with `-DNOMINMAX` and the min and max defined in `<algorithm>` should be used.

I created a patch on my fork (6b5d9a34289757fd874bdd8c5798ad6880abaeb2), if there is interest in this issue, I could rebase and sent it as a pull request.

**Comment by dashesy** [comment]
This looks like a good change, feel free to make that a PR. I finally have some time to fix some of the long-standing issues.

**Comment by dashesy** [comment]
resolved by #66 thanks to @cboulay
