### ISSUE TITLE
Document default sample rate groups

### ISSUE THREAD

**Issue by FloFra** [dashesy/CereLink#53]
Currently there is no note about the default sampling groups inside of CBSDK, even though they seem to have been fixed for quite a while.

Central even uses them for their file name extensions (ns1, ns2, ..., ns5) to document the sampling rate the data has been sampled with.

I therefore propose to have a comment inside cbsdk.h describing the default mapping or even define an array similar to this:
```
unsigned int DEFAULT_SAMPLE_RATE_GROUPS[] = { 0, 500, 1000, 2000, 10000, 30000, 30000 };
``` 
... maybe even combined with an enum:
```
enum DefaultSampleGroup {
    NONE = 0,
    RATE_500 = 1,
    RATE_1K = 2,
    RATE_2K = 3,
    RATE_10k = 4,
    RATE_30k = 5,
    RAW = 6
};
```

**Comment by dashesy** [comment]
Also sounds like a good addition, added.
