### ISSUE TITLE
cbpy is missing many functions

### ISSUE THREAD

**Issue by cboulay** [dashesy/CereLink#61]
I was going to prototype a GUI using pyqt, and if performance was good enough I might just keep it in Python, but pretty early on I realized that cbpy is missing many functions.

I'm willing to use cffi to auto-wrap cbsdk.h. This will get all the functionality out of cbsdk without writing much code. Some OOP syntactic sugar can then be layered on top of that to make the library a little easier to use. This is slightly less performant than Cython but has the benefits of being super simple to do and it is PyPy compatible (anyone?).

Is this desirable?

If you think performance of the Python wrapper is an issue then I will instead try to add to the Cython code, at least to get the functionality I need.

**Comment by cboulay** [comment]
Just a status update and leaving some notes here for myself...

* cbsdk.h turned out to have too much C++ code and/or dependence on cbhwlib.h to be wrapped easily by cffi (C-only)
* cerebus/cbpy.h and cerebus/cbpy.cpp make a minimal C-only wrapper around cbsdk.h
    * The reason for C-only, I think, is in case the user does not have Cython but does have a C-compiler. I think an extension module can still be built in those cases.
* cbpy.pxd provides an interface to the API that Cython understands.
* cbpyw.pyx is a Cython module that makes use of cbpy for easy usage in standard Python.

So, after wrestling with cffi for a while, I will get the functionality I need by filling out the Cython approach a little.

**Comment by dashesy** [comment]
Cython approach is the easiest and certainly the cleanest. Whatever functionality that is needed can be wrapped, one at a time.
Before that I tried the C-Python approach and that was too much work.

**Comment by cboulay** [comment]
I started on this with PR #62

**Comment by dashesy** [comment]
Thanks! I will merge it this weekend. Here is the 6.5 version, if you think more people use that version we should rebase it.

**Comment by cboulay** [comment]
Your 6.5 changes are much more extensive than mine. If you are willing to rebase then I would be happy to accept whatever revisions you need to make. If you want me to do it then I will, but it'll probably take a week until I can get to it.

**Comment by dashesy** [comment]
I will merge this, then rebase my 6.5 on top of it. This way we know it is working before adding the 6.5 changes, because that is not tested. Thanks

**Comment by cboulay** [comment]
Please let me know how this is coming along. I have some other issues I will report soon but they don't need to be worked on until your changes are merged in.

**Comment by dashesy** [comment]
There are some merge conflicts I need to resolve. Will certainly finish this weekend.

**Comment by dashesy** [comment]
I merged your changes to the fixes I got from upstream. If you could test that would be great.

**Comment by cboulay** [comment]
Closed with #62
