### ISSUE TITLE
Latest commit breaks build in CkiVersion.rc

### ISSUE THREAD

**Issue by cboulay** [dashesy/CereLink#65]
Using MSVC 2015 Win64

```
2>CereLink\cbmex\..\cbhwlib\CkiVersion.rc(40): error RC2116: expecting number for ID
2>
2>
2>CereLink\cbmex\..\cbhwlib\CkiVersion.rc(40): error RC2108: expected numerical dialog constant
```

I've never used a .rc file before so I have no idea what is expected.

**Comment by cboulay** [comment]
If I comment out that line then I also have to `#define BMI_VERSION_BUILD_NUMBER    19` in BmiVersion.h (I guess it isn't correctly including cbmex/res/cbmex.rc2?). With those two changes I can build again... but I would rather have a correct fix.

**Comment by dashesy** [comment]
It is from upstream, and I do not have Windows build environment. I am going to commit something please try.

**Comment by cboulay** [comment]
That took care of the initial error. Now:

`CereLink\cbmex\..\cbhwlib\CkiVersion.rc(51): error RC2104: undefined keyword or key name: BMI_VERSION_BUILD_NUMBER`

The offending line is
`FILEVERSION BMI_VERSION`

In BmiVersion.h, you have `#define BMI_VERSION           BMI_VERSION_MAJOR,BMI_VERSION_MINOR,BMI_VERSION_BUILD_NUMBER`

But BMI_VERSION_BUILD_NUMBER is only defined in cbmex/res/cbmex.rc2. 

Putting `#include "../cbmex/res/cbmex.rc2"` at the top of BmiVersion.h fixes it.

**Comment by dashesy** [comment]
I included the header file in `cbmex` now, it makes more sense because not everything should depend on `cbmex`

**Comment by cboulay** [comment]
That fixed it, thanks! I can build the libs and testcbsdk in Win32 and Win64.
cbmex is failing but I will take care of that in my next PR.
