### ISSUE TITLE
Default install dir for 64-bit libs is not on search path in MacOS.

### ISSUE THREAD

**Issue by cboulay** [dashesy/CereLink#67]
Currently the libs are installed to /usr/local/lib64. This is not on the search path so binaries that are linked to libcbsdk.dylib using @rpath cannot find it at runtime.

This has an easy fix in CMakeLists.txt but I want to know what the expected behaviour is in Linux before I make any changes. @dashesy , should the linux libs be installed into $base/lib64 or $base/lib ?

**Comment by dashesy** [comment]
It is distro specific! My fedora box installs to `$base/lib64`. Cmake should install in the correct directory, and also link to correct one (i.e. it should not be hard-coded in Linux).

**Comment by dashesy** [comment]
From [here](https://cmake.org/cmake/help/v3.0/command/find_library.html):

> If the global property FIND_LIBRARY_USE_LIB64_PATHS is set all search paths will be tested as normal, with “64/” appended, and with all matches of “lib/” replaced with “lib64/”. This property is automatically set for the platforms that are known to need it if at least one of the languages supported by the PROJECT command is enabled.

**Comment by cboulay** [comment]
I see what I did: I deleted a line that reset LIB_SUFFIX back to "" on OSX. This LIB_SUFFIX is also used for the dist/ folders so I will have to fix a couple other things.

I need to catch a bus home. I'll do this later tonight.
