### ISSUE TITLE
Memory settings indicated in the wiki are not enough on mac

### ISSUE THREAD

**Issue by piermorel** [dashesy/CereLink#7]
Hello,

I've been trying to run the library on my mac (mac mini late 2012, 16 GB of RAM, 10.8.5). Here are current memory settings, which correspond to the recommended ones wiki:
```
$ sysctl kern.ipc.maxsockbuf
kern.ipc.maxsockbuf: 8388608
$ sysctl kern.sysv.shmmax
kern.sysv.shmmax: 16777216
$ sysctl kern.sysv.shmall
kern.sysv.shmall: 4194304
```
First, for the master version only (not in 6.03), the value of kern.sysv.shmmax  at 16777216 is not enough, I get this error when running testcbsdk:
```
Library memory allocation error
testOpen failed (-26)!
```
If I set it higher:
```
sudo sysctl -w kern.sysv.shmmax=33554432
kern.sysv.shmmax: 16777216 -> 33554432
```
…then this particular error disappears.

Additionally, and in both versions this time, I do get this error with the default settings (after solving the error above):
```
Initializing Cerebus real-time interface 6.03.00.02 (protocol cb3.08)...
Unable to assign UDP interface memory
 Consider using sysctl -w net.core.rmem_max=8388608
 or sysctl -w kern.ipc.maxsockbuf=8388608
testOpen failed (-24)!
Real-time interface already closed
testClose succeeded
```
However, if I change  testcbsdk to require a smaller-sized buffer 
```C
    cbSdkConnection con;
    con.nRecBufSize=(4096*1024);
    cbSdkInstrumentType instType;
    res = cbSdkOpen(INST, conType,con);
```
… I get past this error, even though the maxsockbuf is theoretically large enough !

These are not the last errors I get, but the next ones deserves a separate issue, since they are unrelated.

**Comment by cboulay** [comment]
I ran into this error too. Please re-open to increase visibility as it's not really fixed.
