### ISSUE TITLE
Docs: Need an explanation of SdkSetFileConfig and related functions.

### ISSUE THREAD

**Issue by cboulay** [dashesy/CereLink#70]
Hi all,

I don't quite get how the FileConfig functions work. How is it that sending a packet to the NSP will start/stop file recording? Does the NSP actually record data to disk? Isn't it up to the client computer to retrieve data then store it? [Here](https://github.com/dashesy/CereLink/blob/master/cbmex/cbsdk.cpp#L2377) is an example of a function that I'm referring to.

**Comment by dashesy** [comment]
It is up to the client, but any packet that is sent to NSP will be responded back. So two computers can talk to each other.

**Comment by cboulay** [comment]
That clears it up. Thanks!
