### ISSUE TITLE
cbpy import error

### ISSUE THREAD

**Issue by JohnV7** [dashesy/CereLink#77]
When trying to import cbpy
`import cerebus.cbpy`
I get this error:

> cerebus/cbpy.so: undefined symbol: _Z21cbsdk_init_trial_contiiP15_cbSdkTrialCont

I don't know if this is related to [#23](https://github.com/dashesy/CereLink/issues/23).

Thanks,
John

**Comment by cboulay** [comment]
Hi John,

I've made quite a few changes to the Python wrapper. I meant to make a PR but got sidetracked. I'll do that next.

You can try my fork&branch now if you like: https://github.com/SachsLab/CereLink (defaults to Production branch). I've tested it on Windows, Mac OS Sierra, and Linux Ubuntu 16.04. All were with Python 3 but I don't think there's anything in there that requires 3 over 2.

**Comment by JohnV7** [comment]
yes, this worked. Many thanks!!

I thought cbpy has also functions to import nev and nsx files, but it doesn't seem like that.
Is there any direct way to do this, or do I have to  use n2h5 and h5py ?

**Comment by cboulay** [comment]
Blackrock has [brPY](http://blackrockmicro.com/wp-content/uploads/2016/08/brPY.zip) for loading nev and nsx files via Python.

**Comment by JohnV7** [comment]
thanks for the link, I had already tried brpy. The problem is that for continuous data you can import a specific time range, but for spike-data this option is not implemented. I guess I have to contact blackrock developers directly.
