### ISSUE TITLE
7.0

### ISSUE THREAD

**Issue by cboulay** [dashesy/CereLink#80]
I've been working on updating to 7.0: https://github.com/SachsLab/CereLink/tree/Production_7.0

Unfortunately, my NSP is running an older protocol so I can't test if it works or not on my own hardware. Well, I can test, but it has the expected error that it returns twice as many channels as are set because the new protocol expects each channel to occupy half as much data while my device is using the old protocol. I sent some compiled 7.0 libs to Blackrock and asked them to test, but I probably should have sent a sample application too.

If anyone has an NSP running 7.0 then I'd greatly appreciate it if they could test.
@dashesy , if you get time to look at the official 7.0 headers and see that I completely missed something then please let me know.

**Comment by dashesy** [comment]
You can ask Blackrock to send you nPlayServer with version 7.0 to test. If you get the code you can compile for Linux using make command.
I will look at the headers. Also added you as a contributor, you have nice additions that users will benefit from the sooner they are available. You have a fork but feel free to merge your changes back, or do a PR so I can review first.

**Comment by cboulay** [comment]
Thanks! I will always do a PR before I submit any changes. I might merge directly if I'm fixing my own mistake.

>If you get the code you can compile for Linux using make command.

Is that in reference to Blackrock's cbsdk source code? If it compiles for Linux out of the box then why do they only release Windows binaries?

**Comment by dashesy** [comment]
It is the source code for nPlayServer/NSP. You can use (or at least used to be able to) `make player` to create nPlayServer for Linux/OSX/Windows.
You can ask them to compile, or give you the code to compile. They may ask you to sign NDA.

**Comment by cboulay** [comment]
Ah, I see. Well, I don't mind doing the nPlayServer testing on Windows. If CereLink + cbpy 7.0 works with nplay 7.0 on Windows then I'll be comfortable upgrading my NSP's firmware, and then with the upgraded NSP I can test on Linux/Mac.

**Comment by dashesy** [comment]
Sent nPlayServer 7.0 to your email.

**Comment by cboulay** [comment]
I never received your e-mail, but today I was finally able to test using the nPlayServer.exe that comes with the Windows distribution. My Production_7.0 branch + its Python wrapper + my Python-based visualization tools all seemed to work well.

**Comment by dashesy** [comment]
I sent it again to your email! if not received let me know. It could be the zip file makes it go to your spam folder

**Comment by DingkunLiu** [comment]
Hi, I'd like to ask if the central suite have a build on linux platform?

**Comment by cboulay** [comment]
@DingkunLiu This should probably be a different issue as it doesn't have anything to do with this issue.

Anyway, I am pretty sure the answer is no. It seems that a lot of the Blackrock software makes heavy use of windows libraries. Luckily, CereLink is cross-platform and it enables you to do most of what you can do with Central, if you are willing to put it into an app.

**Comment by cboulay** [comment]
7.0 has been merged into master for a while now. Closing.
