### ISSUE TITLE
How can I convert continuous data's unit to mV

### ISSUE THREAD

**Issue by DingkunLiu** [dashesy/CereLink#86]
It seems the SDK returns continuous data as type int16. So how could I convert it to double with unit mV based on channel config or some other information?

**Comment by cboulay** [comment]
[cbSdkGetChannelConfig](https://github.com/dashesy/CereLink/blob/master/cbmex/cbsdk.h#L514) fills a [cbPKT_CHANINFO struct](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.h#L1937-L1998) containing [cbSCALING  physcalin](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.h#L835-L866).

I assume you are still using Python? Unfortunately, it seems the Python wrapper doesn't relay cbSCALING [see here](https://github.com/dashesy/CereLink/blob/master/cerebus/cbpy.pyx#L576). I can't remember why, if I ever knew.

**Comment by DingkunLiu** [comment]
Yes, I'm using python wrapper. Currently I can only manually transform the unit. And I think it is unsafe and ugly...

**Comment by cboulay** [comment]
Super late answer but I came across this today.

```Python
sampling_rates = [500, 1000, 2000, 10000, 30000, 30000]
smp_grp_info = []
id_grp_map = {}
for smp_grp, smp_rate in enumerate(sampling_rates):
    res, chans_info = cbpy.get_sample_group(smp_grp + 1, instance=self.instance)  # 1-based
    for chan_ix, chan_info in enumerate(chans_info):
        do_something_with(chan_info['gain'], chan_info['unit'])
```
This was 0.25, 'uV' on my system ==> 0.25 uV per bit.
