### ISSUE TITLE
'waveform' option in cbmex unsupported ?

### ISSUE THREAD

**Issue by piermorel** [dashesy/CereLink#9]
Hello,

With my current configuration, I just tried the real-time link between matlab and the nsp. I can get continuous data and spike data, but no spike waveforms. I've tried having them by using:
```
cbmex('trialconfig', 1,'nocontinuous', 'waveform', 400)
```
But I get this error
```
cbSdkSetTrialConfig():
Error using cbmex
Not implemented
```
Is this message to be expected ?

I also noticed that the subsequent calls to cbmex('trialconfig', 1) (even with no 'waveform' requests) give the same errors, unless I close and reopen the connection.

**Comment by cboulay** [comment]
Sorry to revive this old issue, but I couldn't find any `cbGetSpikeCache` in the code. Is there currently any method to get waveforms for display purposes only?

I suppose I could get broad-band continuous data and slice it around event times, but I'm hoping I won't have to do that.

**Comment by cboulay** [comment]
duh. Maybe I should have searched manually instead of relying on github search. `cbSdkGetSpkCache` exists. I'll look into that and see if it gets what I need. Sorry.
