### ISSUE TITLE
 Command line error D8003 : missing source filename

### ISSUE THREAD

**Issue by mmyros** [dashesy/CereLink#90]
Hello,

I am trying to install cbpy on windows 10 with conda's python and  qt 5.9 and getting some errors. Could you help me figure out what's wrong?  

Thank you, 
Max, postdoc

```(base) C:\Users\User\Desktop\CereLink-CereLink7.0>python setup.py install
running install
running bdist_egg
running egg_info
writing cerebus.egg-info\PKG-INFO
writing dependency_links to cerebus.egg-info\dependency_links.txt
writing requirements to cerebus.egg-info\requires.txt
writing top-level names to cerebus.egg-info\top_level.txt
reading manifest file 'cerebus.egg-info\SOURCES.txt'
writing manifest file 'cerebus.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\cerebus
copying cerebus\__init__.py -> build\lib.win-amd64-3.6\cerebus
running build_ext
skipping 'cerebus\cbpy.cpp' Cython extension (up-to-date)
building 'cerebus.cbpy' extension
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
creating build\temp.win-amd64-3.6\Release\cerebus
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\User\Desktop\CereLink-CereLink7.0\dist\include -IC:\Users\User\Desktop\CereLink-CereLink7.0\compat -IC:\Qt5.9\msvc2017_64\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\" /EHsc /Tpcerebus\cbpy.cpp /Fobuild\temp.win-amd64-3.6\Release\cerebus\cbpy.obj
cl : Command line error D8003 : missing source filename
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by cboulay** [comment]
Can you tell a little more about how you got to this point?
Where did you get the CereLink code: from git, from a zip, somewhere else? Which branch?
In order to generate this output, did you run something from a console? Was it a generic console, an Anaconda console, a MSVC console?
What did you run? `pip install .`?

**Comment by mmyros** [comment]
I've tried a few different things and got different errors each time. This
option seems like it got me the closest to success.

In this case, I got cerelink from git, branch 7.0. Then I ran ```python
setup.py install ``` from the Anaconda console.

MSCV console complains that it can't find cbhwlib.h, and an earlier version
of MSCV complains that it can't find stdlib. I don't remember what happens
when I run from cmd but I can check tomorrow.

Please let me know if one of these ways is preferred, or if there is a
better way.

Thanks,
Max

**Comment by mmyros** [comment]
For the record, I could not get python to recognize my environment
variables, so I hard-coded qt path to setup.py.

**Comment by mmyros** [comment]
This was fixed by running from VS2017 console and adding each subfolder in the repo in Include environment variable. I'm still not quite there, but this issue can be closed.

**Comment by cboulay** [comment]
I added some info to a new wiki page [here](https://github.com/dashesy/CereLink/wiki/Install-Python-package).
