### ISSUE TITLE
Move to BSD 3 Licensing

### ISSUE THREAD

**Issue by NHalper** [dashesy/CereLink#92]
Ehsan, 

As we talked about over the phone, I think we are in agreement that it makes sense to license this as BSD 3 to allow more flexible use. Would it be possible to make that conversion in here?

Nick

**Comment by dashesy** [comment]
Pushed the new license [here](https://github.com/dashesy/CereLink/commit/ad8b24c666e519244d74f02e9022bd4f2b096e17) on top of 7.0 branch. @cboulay, please take a look and rebase your work if you would like. The previous license is still available at `7_before_relicense` tag.

**Comment by cboulay** [comment]
I guess I missed when the 7.0 branch was merged into master. I've been using the 7.0 branch, not master. I just took care of all the merges.

BTW the 6.3 branch is pretty stale. It doesn't have anything that isn't in master, and there's a tag for it, so should I delete that branch too?

**Comment by dashesy** [comment]
Yes I merged it to master because it had all the new stuff, while master was stale. Yes feel free to delete it, with tags we can always get that if we want to.

**Comment by cboulay** [comment]
Done. I think this issue is resolved. Please re-open if there needs to be more discussion around the licensing.
