### ISSUE TITLE
Invalid MEX-file error on Ubuntu 18.04 with Matlab R2018b

### ISSUE THREAD

**Issue by jsdpag** [dashesy/CereLink#98]
Dear CereLink community,

We've got a Cerebus with Central 7.04 and NSP firmware 7.04. On a remote system, I'm trying to compile CereLink cbmex* for Matlab R2018b in Ubuntu 18.04.

*I've downloaded the Jan 23rd dashesy/CereLink master branch zip file for this

From a raw install of Ubuntu 18.04 I have added packages:

sudo apt install cmake
sudo apt install python-dev
sudo apt install qt5-default

From GitHub I downloaded the CereLink zip file and unzipped into a place where I have write permissions. I ran cmake ., make all, and make install as instructed.

We did get these errors:

-- Could NOT find HDF5
-- Could NOT find Octave
-- Configuring done
CMake Warning at CMakeLists.txt:260 (ADD_LIBRARY):
  Cannot generate a safe runtime search path for target cbmex because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libQt5Xml.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/MATLAB/R2018b/bin/glnxa64
    runtime library [libQt5Core.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/MATLAB/R2018b/bin/glnxa64

  Some of these libraries may not be found correctly.

In spite of these error messages, everything runs and we find that /usr/local/CereLink/cbmex.mexa64 has been created. But open Matlab and what do we get?

>> cbmex (  'open'  )
Invalid MEX-file '/usr/local/CereLink/cbmex.mexa64': /usr/local/CereLink/cbmex.mexa64: symbol _ZTI9QRunnable version Qt_5 not defined in file
libQt5Core.so.5 with link time reference.

I'm afraid that I just don't understand what this means. If there's anything I can do to help test solutions then please let me know.

Best wishes,
jsdpag

**Comment by jsdpag** [comment]
Thanks cboulay, option 2 was the solution. Matlab R2018b also uses Qt 5.5.

Incidentally, dashesy, I just can't find any man page or google reference to cboct. Qu'est ce que c'est?

**Comment by dashesy** [comment]
@jsdpag cboct is like cbmex but for Octave. If you install `liboctave-dev` cmake will automatically also compile `cboct`
